### ISSUE TITLE
Cosas a corregir

### ISSUE THREAD

**Issue by tomiFuentes9** [tomiFuentes9/tpVinchucasObj2#4]
- Muestra tiene que delegar a otros objetos el filtrado y agregado de opiniones ( Dependiendo del estado del participante se agrega o no se agrega ). Opinion mas frecuente hacer con stream. 
- Sistema, sacar filtro del constructor , hacer seter , almacenar muestra puede recibir directamente una muestra . Avisar a zonas que sea solo un foreach y que si le interesa la muestra haga algo o no . 
- Debatir si zona de cobertura debe tener atributo muestras. 
- Participante , constructor de superclase inicializa lista. 
- Opinar muestra, crear datos de creador solo pasar participante. (Debatir). 
-  Para filtro compuesto hacer objetos and y or 
- Nivel de verificacion hacerlo como superclase y subclase para votos y verificacion.

**Comment by tomiFuentes9** [comment]
Queda:
- Muestra tiene que delegar a otros objetos el filtrado y agregado de opiniones ( Dependiendo del estado del participante se agrega o no se agrega )
- Sistema: Avisar a zonas que sea solo un foreach y que si le interesa la muestra haga algo o no.
- Debatir si zona de cobertura debe tener atributo muestras.
-Opinar muestra, crear datos de creador solo pasar participante. (Debatir)
- Para filtro compuesto hacer objetos and y or
- Nivel de verificacion hacerlo como superclase y subclase para votos y verificacion.

**Comment by tomiFuentes9** [comment]
- Muestra tiene que delegar a otros objetos el filtrado y agregado de opiniones ( Dependiendo del estado del participante se agrega o no se agrega )
- Sistema: Avisar a zonas que sea solo un foreach y que si le interesa la muestra haga algo o no.
- Para filtro compuesto hacer objetos and y or
- Completar docu

**Comment by leandropeppe** [comment]
- Muestra tiene que delegar a otros objetos el filtrado y agregado de opiniones ( Dependiendo del estado del participante se agrega o no se agrega )
- Para filtro compuesto hacer objetos and y or
- Completar docu

**Comment by walterggomez** [comment]
Tp finalizado y aprobado, son unos capos
